### ISSUE TITLE
404 - not found

### ISSUE THREAD

**Issue by JonGilmore** [canchito-dev/spring-security-with-saml2-and-okta#1]
first off, thanks for putting this together, it's a great example and explanation! I'm having an issue with the setup, when I attempt either IDP initiated SSO or SP initiated SSO, I get redirected to `https://localhost:8443/saml/SSO` which throws a 404. I noticed a discrepancy in your screenshot vs what you said should be in the config and I'm wondering if this is the issue? It's shown below: 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/7232986/104849468-657acd80-58af-11eb-9a4b-098dc5a52470.png">

Here's the error I'm getting:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/7232986/104849488-90652180-58af-11eb-824a-b4bbee623637.png">

**Comment by canchito-dev** [comment]
Greetings @JonGilmore. Thank you very much for reporting this discrepancy between what was written and the attached screenshot. The text has been corrected. It should be exactly as in the screenshot.

If you have any other doubt, question or comments, please do not hesitate and contact me.

Regards

**Comment by JonGilmore** [comment]
ah, right on thanks! Little bit closer I think, now I'm facing this: 

![image](https://user-images.githubusercontent.com/7232986/104852054-1e480900-58be-11eb-8206-fd272774be43.png)

I don't get any error logging though, so i'm not entirely sure whats going on. thoughts?

**Comment by JonGilmore** [comment]
Ahh, ok - i missed the part where I had to embed creds into `inMemoryUserDetailsManager`, but I think this possibly exposed a different issue. You suggest as an alternative to use 

```
protected void configure(HttpSecurity http) {
	http
		.authorizeRequests(authorize -> authorize
				.anyRequest().authenticated()
		)
		.saml2Login(withDefaults());
}
```
but, this gives me a `compilation failure` as shown below: 

```
cannot find symbol
[ERROR]   symbol:   method withDefaults()
[ERROR]   location: class com.canchitodev.samldemo.configuration.SecurityConfiguration
```

EDIT: derp, just had to import this: 
```
import static org.springframework.security.config.Customizer.withDefaults;
```
